### ISSUE TITLE
CS0535 & CS0506 -- Another PR is needed so upstream build will no longer be broken

### ISSUE THREAD

**Issue by thomiel** [lytico/Microsoft.Maui.Graphics#12]
I got compiler errors when trying to build (both: upstream and in this repo):

    CS0535 "GtkImage" doesn't implement the interface member "IImage.ToPlatformImage()"
    CS0506 "PlatformCanvas.GetStringSize(string, IFont, float)": The inherited member "AbstractCanvas<PlatformCanvasState>.GetStringSize(string, IFont, float)" can't be overriden because it is not tagged as "virtual" , "abstract" or "override"

Do I still need a more special NuGet package or is it just due to new C# features, because of virtual/override on the GetStringSize() members. (Just messing around with <LangVersion> in the .csproj didn't do anything, though).

Is main still the place to be or do you suggest another lytico/* gtk branch?

I really could use some pointers to not get lost...

**Comment by lytico** [comment]
Work in Progress: https://github.com/lytico/Microsoft.Maui.Graphics/tree/lytico/track_api_changes_net6

**Comment by lytico** [comment]
ICanvasStateService<TState> needs to be implemented
there is already a CanvasState: 
https://github.com/lytico/Microsoft.Maui.Graphics/blob/lytico/track_api_changes_net6/src/Microsoft.Maui.Graphics.Gtk/Gtk/PlatformCanvasState.cs
so this has to be used to implement ICanvasStateService somehow.
Hint: https://github.com/lytico/Microsoft.Maui.Graphics/blob/lytico/track_api_changes_net6/src/Microsoft.Maui.Graphics.Skia/SkiaCanvasStateService.cs

**Comment by lytico** [comment]
DONE: IStringSizeService needs to be implemented. Most of code is in PlatformCanva.Text.cs

**Comment by lytico** [comment]
upstream PR is here: https://github.com/dotnet/Microsoft.Maui.Graphics/pull/469
